version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: liquidity_genai-backend-1
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    container_name: liquidity_genai-db-1
    environment:
      POSTGRES_USER: genai_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: genai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile.streamlit
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - backend

volumes:
    postgres_data: